---
language: ruby
cache:
  directories:
  - vendor/bundle
#  - spec/fixtures/modules
sudo: false
branches:
  only:
    - master
    - develop
bundler_args: --without system_tests
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
matrix:
  fast_finish: true
  include:
  - rvm: 2.4.9
    env: PUPPET_GEM_VERSION="~> 5.5.22"
  - rvm: 2.5.8
    env: PUPPET_GEM_VERSION="~> 6.19.1" FACTER_GEM_VERSION="~> 3.14.14"
  - rvm: 2.7
    env: PUPPET_GEM_VERSION="~> "7.1.0"
notifications:
  email:
    - github@razorsedge.org
